version: '3.9'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    links:
      - php

  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - dbdata:/var/lib/mysql
      - .docker/mysql-dump:/docker-entrypoint-initdb.d

volumes:
  dbdata:
    driver: local